### ISSUE TITLE
Error on line 39

### ISSUE THREAD

**Issue by fu-raz** [neoighodaro/cmpsr.co#1]
When I run cmpsr.php I get this error:

PHP Fatal error:  Uncaught Exception: An error occurred. Err:  in /cmpsr.php:39
Stack trace:
#0 /cmpsr.php(144): cmpsr_install()
#1 {main}
  thrown in /cmpsr.php on line 39

If I dump the response, I get this response from the server:

"{"message":"The given data was invalid.","errors":{"hash":["The hash has already been taken."]}}"

I would love to use this, so I’m hoping I just made a mistake

**Comment by neoighodaro** [comment]
I will look at it after the holidays



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by wisanu21** [comment]
I run cmpsr.php on DraftCode ( iPad Air ) and php v 5.6.30
![BD993030-8436-4155-BE0D-A32951D249A9](https://user-images.githubusercontent.com/50043133/71682847-73080700-2dc3-11ea-86e8-c567df62dc9f.png)

**Comment by wisanu21** [comment]
I update v php 5 to 7 
![DE80D8A2-09BB-43B1-9C2F-D2B84CD7DC26](https://user-images.githubusercontent.com/50043133/71683275-b31bb980-2dc4-11ea-809a-240f746d713c.png)

**Comment by albertogcatalan** [comment]
Hey, I have the same bug in line 39. Could you fix soon?

**Comment by neoighodaro** [comment]
Yeah sure, I have to set a reminder to fix this...

**Comment by Nexulo** [comment]
same bug here. Any news to fix this?

**Comment by neoighodaro** [comment]
Can you try again? @maisen20 @albertogcatalan @fu-raz

**Comment by Josex2021** [comment]
Hello, i have the same bug, And i just tried it, did you change anything in the script?? Thanks in advanced

**Comment by neoighodaro** [comment]
Not that i know of @Josex2021 but you can send a pr

**Comment by bendparker** [comment]
I have the same bug:

PHP Parse error:  syntax error, unexpected ':', expecting '{' in /private//recordsolutions/cmpsr.php on line 23

**Comment by bendparker** [comment]
Fixed the initial error by upgrading to PHP 7, but now get this:

Errors:
PHP Fatal error:  Uncaught Exception: An error occurred. Err:  in /recordsolutions/cmpsr.php:42
Stack trace:
#0 /recordsolutions/cmpsr.php(147): cmpsr_install()
#1 {main}
  thrown in /recordsolutions/cmpsr.php on line 42
